src/Entity/Item.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Entity\Traits\Id;
use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\Index;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Table(
 *     name="pstryk_item",
 *     indexes={@Index(name="slug_idx", columns={"slug"})}
 * )
 * @ORM\Entity(repositoryClass="App\Repository\ItemRepository")
 */
class Item
{
    use Id;

    /**
     * @ORM\Column(type="string", name="album", nullable=false)
     * @Assert\NotBlank()
     * @Assert\Type(type="string")
     */
    private ?string $album = null;

    /**
     * @ORM\Column(type="string", name="title", nullable=false)
     * @Assert\NotBlank()
     * @Assert\Type(type="string")
     */
    private string $title;

    /**
     * @ORM\Column(type="string", name="description", nullable=true)
     * @Assert\Type(type="string")
     */
    private ?string $description = null;

    /**
     * @Gedmo\Slug(fields={"title"}, updatable=false, separator="-")
     * @ORM\Column(name="slug", nullable=true, length=191, unique=true)
     * @Assert\Type(type="string")
     */
    private ?string $slug = null;

    /**
     * @ORM\Column(type="datetime", name="date", nullable=false)
     */
    private DateTime $date;

    /**
     * @ORM\Column(type="decimal", name="latitude", precision=10, scale=8, nullable=true)
     */
    private float $latitude;

    /**
     * @ORM\Column(type="decimal", name="longitude", precision=11, scale=8, nullable=true)
     */
    private float $longitude;

    /**
     * @ORM\Column(type="boolean", name="is_active", nullable=false)
     */
    private bool $isActive = true;

    /**
     * @ORM\OneToMany(targetEntity="Image", mappedBy="item", cascade={"persist"}, orphanRemoval=true)
     * @ORM\OrderBy({"position" = "ASC"})
     */
    private Collection $images;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->date = new DateTime();
    }

    public function addImage(Image $image): self
    {
        $image->setItem($this);

        $this->images[] = $image;

        return $this;
    }

    public function removeImage(Image $image): void
    {
        $this->images->removeElement($image);
    }

    public function getImages(): Collection
    {
        return $this->images;
    }

    public function getMainImage(): ?Image
    {
        /** @var Image $image */
        foreach ($this->images as $image) {
            if ($image->getIsMain()) {
                return $image;
            }
        }

        if (\count($this->images) > 0) {
            return $this->images[0];
        }

        return null;
    }

    public function setAlbum(string $album): self
    {
        $this->album = $album;

        return $this;
    }

    public function setId(int $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function setDate(DateTime $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function setLatitude(float $latitude): self
    {
        $this->latitude = $latitude;

        return $this;
    }

    public function setLongitude(float $longitude): self
    {
        $this->longitude = $longitude;

        return $this;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    public function getAlbum(): ?string
    {
        return $this->album;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getDate(): ?DateTime
    {
        return $this->date;
    }

    public function getLatitude(): float
    {
        return $this->latitude;
    }

    public function getLongitude(): float
    {
        return $this->longitude;
    }

    public function getIsActive(): bool
    {
        return $this->isActive;
    }

    public function getGuid(): string
    {
        return \sprintf('%s_%s', $this->getAlbum() ?? '', md5((string) $this->getId()));
    }
}

src/Controller/AlbumController.php
<?php declare(strict_types=1);

namespace App\Controller;

use App\Controller\Helper\CounterHelper;
use App\Controller\Helper\DomainHelper;
use App\Exception\RecordNotFoundException;
use App\Provider\AlbumProvider;
use App\Provider\ItemProvider;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AlbumController extends AbstractController
{
    public function __construct(private readonly ItemProvider $itemProvider, private readonly AlbumProvider $albumProvider, private readonly DomainHelper $domainHelper, private readonly CounterHelper $counterHelper)
    {
    }

    /**
     * @Route("/{page}", name="app_album_index", requirements={"page" = "\d+"}, defaults={"page" = "1"})
     */
    public function index(int $page): Response
    {
        /* @noinspection PhpUnhandledExceptionInspection */
        $album = $this->domainHelper->getCurrentAlbum();

        $this->counterHelper->increment($album->getSlug());

        /* @noinspection PhpUnhandledExceptionInspection */
        $items = $this->itemProvider->getAllPaginated(
            $album->getSlug(),
            $page,
            $this->albumProvider->getBySlug($album->getSlug())->getPaginationLimit()
        );

        /* @noinspection PhpUnhandledExceptionInspection */
        return $this->render(\sprintf('album/%s/index.html.twig', $album->getSlug()), [
            'items' => $items,
            'album' => $this->albumProvider->getBySlug($album->getSlug()),
        ]);
    }

    /**
     * @Route("/{itemSlug}", requirements={"itemSlug" = "^((?!feed|sitemap|zaplecze|robots\.txt|sitemap\.xml).)*$"}, name="app_album_item")
     */
    public function item(string $itemSlug): Response
    {
        /* @noinspection PhpUnhandledExceptionInspection */
        $album = $this->domainHelper->getCurrentAlbum();

        try {
            $item = $this->itemProvider->getBySlug($album->getSlug(), $itemSlug);
        } catch (RecordNotFoundException) {
            return $this->redirectToRoute('app_album_index');
        }

        $this->counterHelper->increment($album->getSlug());

        /* @noinspection PhpUnhandledExceptionInspection */
        return $this->render(\sprintf('album/%s/item.html.twig', $album->getSlug()), [
            'item' => $item,
            'next_item' => $this->itemProvider->getNext($item),
            'prev_item' => $this->itemProvider->getPrevious($item),
            'album' => $this->albumProvider->getBySlug($album->getSlug()),
        ]);
    }
}

templates/album/pstryk/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{{ block('title') }} ‒ {{ album.title }}</title>
        {% block stylesheets %}{{ encore_entry_link_tags(album.slug) }}{% endblock %}
        <base href="{{ getRoute(null) }}">
        <meta name="author" content="Rafał Toborek">
        <meta name="copyright" content="Rafał Toborek">
        <meta name="robots" content="index, follow">
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <meta name="description" content="{{ block('description')|striptags }}">
        <meta property="og:type" content="website">
        <meta property="og:url" content="{{ getRouteWithPagination('') }}">
        {% if block('image') is defined %}
            <meta property="og:image" content="{{ block('image') }}">
        {% endif %}
        <meta property="og:title" content="{{ block('title') }}">
        <meta property="og:description" content="{{ block('description')|striptags }}">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="shortcut icon" type="image/x-icon" href="{{ asset('assets/images/favicon/pstryk.png') }}">
        <link rel="alternate" type="application/rss+xml" title="{{ album.title }} RSS" href="{{ album.feedUrl }}">
        <link rel="sitemap" type="application/xml" title="Sitemap" href="/sitemap.xml">
    </head>
    <body>
        <div class="container">
            <main>
                {% block body %}{% endblock %}
            </main>

            <footer>
                <div class="row">
                    <div class="col-12 col-md-5 text-center align-self-center">
                        <a href="https://kontakt.toborek.info" target="_blank">Napisz do mnie</a> lub
                        <a href="{{ album.feedUrl }}" target="_blank">zasubskrybuj kanał RSS</a><br>
                        Przejrzyj listę <a href="{{ getRoute('sitemap') }}">wszystkich albumów</a>
                    </div>
                    <div class="col-12 col-md-2 text-center footer-social">
                        <div class="svg-story"></div>
                    </div>
                    <div class="col-12 col-md-5 text-center align-self-center">
                        Z potrzeby serca &copy; 2020-{{ 'now'|date('Y') }}  <a href="https://toborek.info" target="_blank">Rafał Toborek</a>
                        <br>
                        Proszę nie upubliczniać bez wcześniejszej zgody
                    </div>
                </div>

                {{ getSeoButtons({
                    'backgroundColor': '#313131',
                    'fontColor': '#484848',
                    'hoverBackgroundColor': '#464646',
                    'hoverFontColor': '#fff',
                    'fontSize': '12px',
                    'anchorPadding': '8px 7px',
                    'padding': '0',
                    'radius': '3px'
                })|raw }}
            </footer>
        </div>

        {{ encore_entry_script_tags(album.slug) }}
        {{ getMatomoCode(19)|raw }}

        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/album/pstryk/index.html.twig
{% extends 'album/pstryk/base.html.twig' %}

{% block title %}Rafał Toborek{% endblock %}
{% block description %}Czas płynie, a ja staram się pozostawić swój ślad...{% endblock %}
{% block image %}{% if items[0] is defined and items[0].mainImage is not empty %}{{ getRoute(null) }}/{{ items[0].mainImage.filePath.thumbPublicPath }}{% endif %}{% endblock %}

{% block body %}
    {% if items is defined %}
        {% for item in items %}
            <div class="row frame">
                <div class="frame-title col-12 text-center">
                    <a href="{{ getRoute(item.slug) }}">{{ item.title }}</a>
                </div>

                <div class="frame-date col-12 text-center" data-date="{{ item.date|date('r') }}" title="{{ item.date|date('Y . m . d') }}">
                    {{ item.date|date('Y . m . d') }}
                </div>

                {% if item.description is not empty %}
                    <div class="frame-description col-12 text-center">
                        {{ item.description|nl2br }}
                    </div>
                {% endif %}

                <div class="frame-thumb col-12 text-center">
                    <a href="{{ getRoute(item.slug) }}">
                        {% if item.mainImage is not empty %}
                            <img src="{{ item.mainImage.filePath.thumbPublicPath }}" class="img-fluid"
                                 width="{{ item.mainImage.imageDetails.thumbWidth }}"
                                 height="{{ item.mainImage.imageDetails.thumbHeight }}"
                                 alt="{{ item.title }}">
                        {% endif %}
                    </a>
                </div>
            </div>
        {% endfor %}
    {% endif %}

    <div class="paginator">
        <div class="col-12">
            {{ knp_pagination_render(items, template = 'album/parts/pagination.html.twig', viewParams = {'align': 'center'}) }}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ include('album/pstryk/item_js.html.twig') }}
{% endblock %}

templates/album/pstryk/item.html.twig
{% extends 'album/pstryk/base.html.twig' %}

{% block title %}{{ item.title }}{% endblock %}
{% block description %}{{ item.description }}{%  endblock %}
{% block image %}{% if item.mainImage is defined and item.mainImage is not empty %}{{ getRoute(null) }}/{{ item.mainImage.filePath.thumbPublicPath }}{% endif %}{%  endblock %}

{% block body %}
    <div class="row frame-item">
        <div class="frame-item-title col-12 text-center">
            {{ item.title }}
        </div>

        <div class="frame-item-date col-12 text-center" data-date="{{ item.date|date('r') }}" title="{{ item.date|date('Y . m . d') }}">
            {{ item.date|date('Y . m . d') }}
        </div>

        {% if item.description is not empty %}
            <div class="frame-item-description col-12 text-center">
                {{ item.description|nl2br }}
            </div>
        {% endif %}

        <span class="frame-item-image-gallery">
            {% for image in item.images %}
                <div class="frame-item-thumb col-12 text-center">
                    <a href="{{ image.filePath.imagePublicPath }}">
                        <img src="{{ image.filePath.thumbPublicPath }}" class="img-fluid"
                             width="{{ image.imageDetails.thumbWidth }}"
                             height="{{ image.imageDetails.thumbHeight }}"
                             alt="{% if image.description is empty %}{{ item.description }}{% else %}{{ image.description }}{% endif %}">
                    </a>
                </div>

                {% if image.description is not empty %}
                    <div class="col-12 frame-item-image-description text-center">
                        {{ image.description|nl2br }}
                    </div>
                {% endif %}
            {% endfor %}
        </span>
    </div>

    <div class="row item-menu-bottom">
        {{ include('album/pstryk/item_menu.html.twig') }}
    </div>
{% endblock %}

{% block javascripts %}
    {{ include('album/pstryk/item_js.html.twig') }}
{% endblock %}

templates/album/pstryk/sitemap.html.twig
{% extends 'album/pstryk/base.html.twig' %}

{% block title %}Wszystkie albumy{% endblock %}
{% block description %}Wszystkie albumy posortowane na podstawie lat.{% endblock %}

{% block body %}
    <div class="row frame-item">
        <div class="frame-item-title col-12 text-center">
            {{ block('title') }}
        </div>

        {% if history is defined %}
            <div class="frame-history col-12">
                <ul class="frame-history-year">
                    {% for year, items in history %}
                        <li>
                            {{ year }}
                            <ul class="frame-history-items">
                                {% for item in items %}
                                    <li><a href="{{ getRoute(item.slug) }}">{{ item.title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock %}